# This is a basic workflow to help you get started with Actions

name: PacManCI

# Controls when the workflow will run
on: [push, pull_requests, workflow_dispatch]

  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Running PacMan game!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          javac -cp "Projects/P1/src/" Projects/P1/src/*.java
